# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b31250e59d7fe48f64b60b5b66eb2beb9cd6392f5c6adcfc2f3909e6cc4ed9de34f3e8f56f1156512c4ae647beb5380b6fc8a900a111a96351e313c66e3ba4

test:
  secret_key_base: 565b32386a72917ee344b46e55d086a53462f4e4b1ad296cfcd7857362a7d430ee45b3a64def3040613e8a7d5957762ff19c9eb141700f0db608435bf8e607e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
